#!/bin/bash

if [ "$(whoami)" != "root" ]; then
   echo "This needs to be run as root"
   exit 1
fi
virsh -q list --all 2>/dev/null | grep -q SNO
if [ $? -eq 0 ]; then
    virsh undefine SNO
else
    echo "VM SNO not found"
    exit 1
fi
virsh -q list --state-running --state-paused 2>/dev/null | grep -q SNO
if [ $? -eq 0 ]; then
    virsh shutdown --domain SNO --mode acpi
fi

virsh vol-delete SNO.qcow2 --pool default
echo "It may take a minute for everything to clean up..."

echo "New /etc/hosts file:"
D=${BASEDOMAIN:-$(cat config.yaml | yq .sno.domain)}
C=${CLUSTERNAME:-$(cat config.yaml | yq .sno.name)}
T=$(mktemp)

awk "/${C}.${D}/ { next } { print }" /etc/hosts | tee ${T}
mv ${T} /etc/hosts
chmod 644 /etc/hosts
