#!/bin/bash

export LIBVIRT_DEFAULT_URI=qemu:///system

virsh -q list --all 2>/dev/null | grep -q SNO
if [ $? -eq 0 ]; then
    virsh undefine SNO
    virsh -q list --state-running --state-paused 2>/dev/null | grep -q SNO
    if [ $? -eq 0 ]; then
        virsh shutdown --domain SNO --mode acpi
    fi

    virsh vol-delete SNO.qcow2 --pool default
else
    echo "VM SNO not found"
fi

# We need to get the IP address!
MAC=00:11:22:33:44:55
IP=$(virsh -q net-dhcp-leases default --mac ${MAC} 2>/dev/null | gawk '{print $5}' | cut -d/ -f1)
if [ $? -eq 0 ]; then
    virsh net-update --network default --command delete --section dns-host --xml "<host ip='${IP}'></host>"

    D=${BASEDOMAIN:-$(cat config.yaml | yq .sno.domain)}
    C=${CLUSTERNAME:-$(cat config.yaml | yq .sno.name)}
    T=$(mktemp)

    awk "/${C}.${D}/ { next } { print }" /etc/hosts > ${T}
    echo "Need to cleanup /etc/hosts (sudo may prompt for password)"
    sudo mv ${T} /etc/hosts
    sudo chmod 644 /etc/hosts
    echo "It may take a minute for everything to clean up..."
fi
